spring:
  config:
    import: optional:file:.env[.properties]

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

weather:
  openweather:
    url: https://api.openweathermap.org/data/3.0/onecall
    key: ${OPENWEATHER_API_KEY}
  airkorea:
    url: https://apis.data.go.kr/B552584/ArpltnInforInqireSvc/getMsrstnAcctoRltmMesureDnsty
    key: ${DUST_API_KEY}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        highlight_sql: true
        default_batch_fetch_size: 1000
    open-in-view: false

logging:
  level:
    org.hibernate.SQL: debug
