spring:
  application:
    name: develop1
  profiles:
    active: dev # 서버 환경 : dev | 로컬 환경 : local


springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /
    groups-order: ASC
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: alpha
    tags-sorter: alpha

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health
external:
  openweather:
    url: https://api.openweathermap.org/data/3.0/onecall
    key: ${OPENWEATHER_API_KEY}
  airkorea:
    url: https://apis.data.go.kr/B552584/ArpltnInforInqireSvc/getMsrstnAcctoRltmMesureDnsty
    key: ${DUST_API_KEY}
